name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-line-length=80 --ignore=E111,E121,E126 --statistics
      - name: install coverage tool for Receiver
        run: |
         sudo apt-get update
         sudo apt-get install -y gcovr
      - name: build for Receiver
        run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o Receiver Receiver/*.c      
      - name: Pipeline Sender and receiver
        run: python sender.py | ./Receiver
      - name: Run and collect coverage
        run: |
          coverage run -m pytest
          coverage html
          coverage report
      - name: Upload coverage for Sender
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./htmlcov
          retention-days: 21
      - name: collect coverage for Receiver
        run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html --print-summary
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./*.html
          retention-days: 21
